### PR TITLE
Added Django 2.0 support

### PR DESCRIPTION
**Pull request by marazmiki**
Added Django 2.0 support

### CODE REVIEW

**Comment by Fingel** [comment]
This PR does a lot more than just add Django2.0 support. Maybe @klen would be more receptive to it if the PR also didn't mess with tox, .gitignores, and all the other stuff that doesn't actually fix the issue. Plus you might want to squash commits like "Oops, forgot about env" as it clutters the git history.

**Comment by marazmiki** [comment]
> Maybe @klen would be more receptive to it if the PR also didn't mess with tox, .gitignores, and all the other stuff that doesn't fix the issue.

I suppose @klen could mention it and ask me to fix if it's was a reason. Disagreed with your thesis about tox: it needs it because, without these changes, Travis CI builds fails.

> Plus you might want to squash commits like "Oops, forgot about env" as it clutters the git history.

Actually, I've pushed it accidentally and will definitely squash it, if @klen would ask for this. But no any reaction. So I ask myself, should I do it?

**Comment by klen** [comment]
@marazmiki Great PR, Thank you!

**Comment by klen** [comment]
There still some conflicts with the branch so I'm going to close it, but the PR was merged.

@marazmiki I also drop support for Django 1.10-. Anybody can use old mixer versions.

**Pull request closed without merging**
